FROM python:3.14-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends --no-install-suggests -qq --yes \
    curl && \
    rm -rf /var/lib/apt/lists/*

RUN pip install uv

WORKDIR /opt/users

COPY scripts/users.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
