"""developers and memberships

Revision ID: f9f47c9e6839
Revises: e37d04bc88f2
Create Date: 2026-08-18 00:29:09.435142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9f47c9e6839'
down_revision: Union[str, None] = 'e37d04bc88f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developers_owner_user_id'), 'developers', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_developers_slug'), 'developers', ['slug'], unique=True)
    op.create_table('memberships',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('developer_id', sa.Uuid(), nullable=False),
    sa.Column('builder_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['builder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('developer_id', 'builder_id', name='uq_membership_developer_builder')
    )
    op.create_index(op.f('ix_memberships_builder_id'), 'memberships', ['builder_id'], unique=False)
    op.create_index(op.f('ix_memberships_developer_id'), 'memberships', ['developer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberships_developer_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_builder_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_developers_slug'), table_name='developers')
    op.drop_index(op.f('ix_developers_owner_user_id'), table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###
